# Generated by Django 5.1.7 on 2025-05-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('workout_type', models.CharField(choices=[('cardio', 'Cardio'), ('weight_strength', 'Weight-Strength'), ('calisthenics', 'Calisthenics'), ('stretching', 'Stretching')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
