# Generated by Django 5.1.7 on 2025-05-01 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='workout_type',
            new_name='type',
        ),
    ]
