# Generated by Django 5.1.7 on 2025-05-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_tracker', '0002_rename_workout_type_workout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('weight strength', 'Weight Strength'), ('calisthenics', 'Calisthenics'), ('stretching', 'Stretching')], max_length=20),
        ),
    ]
