# Generated by Django 5.1.7 on 2025-05-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_tracker', '0003_alter_workout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('strenght', 'Strenght'), ('calisthenics', 'Calisthenics'), ('stretching', 'Stretching')], max_length=20),
        ),
    ]
