# Generated by Django 5.1.7 on 2025-05-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_tracker', '0004_alter_workout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('weightlifting', 'Weightlifting'), ('calisthenics', 'Calisthenics'), ('stretching', 'Stretching')], max_length=20),
        ),
    ]
