# Generated by Django 5.1.7 on 2025-05-15 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_tracker', '0005_alter_workout_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('cardio', 'Cardio'), ('calisthenics', 'Calisthenics'), ('weightlifting_upper', 'Weightlifting Upper Body'), ('weightlifting_lower', 'Weightlifting Lower Body')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='custom_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness_tracker.customexercise'),
        ),
    ]
