# Generated by Django 5.1.7 on 2025-05-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_tracker', '0007_remove_workout_custom_exercise_remove_workout_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customexercise',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
