# Generated by Django 5.1.7 on 2025-05-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_tracker', '0008_alter_customexercise_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='exercise_type',
        ),
    ]
